// THIS IS AN AUTOGENERATED FILE BY CREATE-WEB3-DAPP

export type CW3DConfig = {
	mainnetName: string;
	mainnetChainId: number;
	testnetChainId: number;
	testnetChainName: string;
};

const config = {
	mainnetName: "base-mainnet",
	mainnetChainId: 8453,
	testnetChainId: 84532,
	testnetChainName: "base-sepolia",
} as const satisfies CW3DConfig;

export default config; 